### PR TITLE
update requirements

### PR DESCRIPTION
**Pull request by yuri20198**

### CODE REVIEW

**Comment by ianzhao05** [comment]
Thanks for the PR. Last I checked, the newer versions of `pytesseract` caused some issues, so I will do some testing. Also, any reason that you removed the shebang on the Python script?

**Comment by yuri20198** [comment]
I didn't notice any problem with latest version of pytesseract.
I'm using it on windows, so no special reason of shebang line 
And I found os library was imported, but not used in the rest of code.

**Comment by ianzhao05** [comment]
Yes, thank you for noticing the unused `os` import. I would prefer to leave the shebang in to for maximum cross-platform support.

I'm still getting an issue with `pytesseract==0.3.7`, similar to madmaze/pytesseract#314 actually. It is apparently a Tesseract issue, but rolling back to `pytesseract==0.3.4` fixes it for some reason. I don't think there are any major improvements in the newest version, so I would prefer to leave the version at its old one. The other upgrades seem good!

**Comment by yuri20198** [comment]
I've kept shebang line and pytesseract version in new commit

**Comment by ianzhao05** [comment]
Thanks, looks good :)

**Pull request merged**
