### PR TITLE
Make the code packageable

### LINKED ISSUE #54: Consider adding pyproject.toml for package installation
Here is a ` pyproject.toml`  example
```
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "textshot"
version = "0.0.1"
authors = [
  { name="Ian ianzhao05", email="author@example.com" },
]
description = "Python tool for grabbing text via screenshot"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.urls]
"Homepage" = "https://github.com/ianzhao05/textshot"
"Bug Tracker" = "https://github.com/ianzhao05/textshot/issues/"

[project.scripts]
textshot = "textshot.textshot:main"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.packages.find]
where = ["textshot"]

```
It may need some tweaking and modifying the project to relocate python files in `textshot`  and changing the way import is done by using something like `from .ocr import …` for example.

It would be helpful to make a working package for linux distributions.

You then build and install the package with:
```
python3 -m build --wheel
python -m installer dist/*.whl
```

### PR DESCRIPTION
**Pull request by matclab**
This will allow to make a proper AUR package in Arch linux (the current one doesn't work
close #54

### CODE REVIEW

**Comment by matclab** [comment]
This PR would allow solving problem on https://aur.archlinux.org/packages/textshot-git (and would allow textshot to be easily packageable for other distributions)

**Comment by ianzhao05** [comment]
Hi, thanks for this, it looks great. I'm not super familiar with packaging Python, and after playing around a bit I found I needed to make two changes to `pyproject.toml` to make it work for me. First, I changed the build system to `setuptools` so it would recognize `requirements.txt`. Then, I had some import errors so I removed `[tool.setuptools.packages.find] where = ["textshot"]`.

I've tested it on two machines, and it seems to work smoothly so far. Thanks again for the suggestion and the PR; please let me know if I changed something I shouldn't have.

**Comment by matclab** [comment]
@ianzhao05 everything looks good to me (I'm not very famliliar with python packaging process either, but `pip install` works and `python -m build` also.

**Comment by ianzhao05** [comment]
@matclab Thanks for your help with this. I have also published it on pypi now so installation should be even easier!

**Pull request merged**
